spring.application.name=userservice
# The address of Docker database
spring.datasource.url=jdbc:postgresql://localhost:5432/userdb
spring.datasource.username=ticketuser
spring.datasource.password=ticketpassword

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true